import { CharacterId } from '../types/game';

export interface CharacterConfig {
  id: CharacterId;
  name: string;
  subtitle: string;
  description: string;
  skillName: string;
  skillKey: string;
  skillDescription: string;
  skillCooldown: number; // in secondi
  tag: string;
  color: string;
  accentColor: string;
}

export const CHARACTERS: Record<CharacterId, CharacterConfig> = {
  shhte: {
    id: 'shhte',
    name: 'Shhte',
    subtitle: 'Hacker Sabaudo & Cyber-Runner',
    description: 'Il creatore e programmatore di Super Turin. Maestro dell\'overclocking dei sistemi torinesi.',
    skillName: 'Matrix Overclock',
    skillKey: 'SPACE',
    skillDescription: 'Rallenta il tempo e i nemici al 35% per 4s, conferendo velocità supersonica 1.8x.',
    skillCooldown: 12.0,
    tag: '⚡ SPEED & TIME',
    color: '#06b6d4',
    accentColor: '#38bdf8',
  },
  ugo: {
    id: 'ugo',
    name: 'Ugo',
    subtitle: 'Il Brawler dei Murazzi',
    description: 'Veterano delle notti torinesi lungo il Po. Forza pura capace di scuotere il selciato.',
    skillName: 'Terremoto dei Murazzi',
    skillKey: 'SPACE',
    skillDescription: 'Schianto tellurico che stordisce ed elimina all\'istante tutti i nemici a terra nel raggio di 450px.',
    skillCooldown: 9.0,
    tag: '💥 TANK & STOMP',
    color: '#ef4444',
    accentColor: '#b91c1c',
  },
  jari: {
    id: 'jari',
    name: 'Jari',
    subtitle: 'L\'Acrobata Ninja del Valentino',
    description: 'Agilissimo acrobata urbano dei parchi torinesi. Raggiunge altezze inaccessibili a chiunque.',
    skillName: 'Salto Jet & Planata Reale',
    skillKey: 'SPACE',
    skillDescription: 'Spinta a razzo verticale aerea con scia infuocata, seguita da 3.5s di planata fluttuante.',
    skillCooldown: 8.0,
    tag: '🪂 AIR GLIDER',
    color: '#10b981',
    accentColor: '#059669',
  },
  jonson: {
    id: 'jonson',
    name: 'Jonson',
    subtitle: 'Il Guastatore Pesante',
    description: 'Tiratore scelto e collezionista di artiglieria pesante delle officine industriali.',
    skillName: 'Raffica a Ventaglio 5x',
    skillKey: 'SPACE',
    skillDescription: 'Spara una devastante salva di 5 colpi a cono che spazza via corridoi di nemici e blocchi ?.',
    skillCooldown: 7.0,
    tag: '🎯 HEAVY MARKS',
    color: '#f59e0b',
    accentColor: '#d97706',
  },
  krebs: {
    id: 'krebs',
    name: 'Krebs',
    subtitle: 'Il Biochimico delle Sostanze',
    description: 'Genio della chimica farmaceutica torinese. Manipola il ciclo biologico delle sostanze psichedeliche.',
    skillName: 'Aura Tossica & Bio-Cura',
    skillKey: 'SPACE',
    skillDescription: 'Genera un anello di bio-spore tossiche per 5s che scioglie i nemici e rigenera subito +1 Cuore!',
    skillCooldown: 15.0,
    tag: '🧪 HEAL & TOXIC',
    color: '#a855f7',
    accentColor: '#9333ea',
  },
  devis: {
    id: 'devis',
    name: 'Devis',
    subtitle: 'Il Demone Spettrale della Notte',
    description: 'Spirito enigmatico delle gallerie sotterranee di Pietro Micca. Inafferrabile e spietato.',
    skillName: 'Fase Spettrale (Incorporeo)',
    skillKey: 'SPACE',
    skillDescription: 'Diventa etereo per 4s: totale invulnerabilità ai danni, scatto +100% e attraversa nemici ed ostacoli.',
    skillCooldown: 10.0,
    tag: '👻 PHANTOM DASH',
    color: '#6366f1',
    accentColor: '#4f46e5',
  },
  willy: {
    id: 'willy',
    name: 'Willy',
    subtitle: 'Il Giocatore d\'Azzardo Reale',
    description: 'Nobile dandy torinese appassionato di scommesse e piogge dorate di cioccolato.',
    skillName: 'Jackpot Sabaudo',
    skillKey: 'SPACE',
    skillDescription: 'Evoca dal cielo una pioggia di 6 gianduiotti esplosivi, regala +500 punti e un power-up a sorpresa!',
    skillCooldown: 14.0,
    tag: '🎰 GOLD JACKPOT',
    color: '#ffd166',
    accentColor: '#ffb703',
  },
  benedetta: {
    id: 'benedetta',
    name: 'Bennipi',
    subtitle: 'La Duchessa Reale dei Portici',
    description: 'Elegante nobildonna dei salotti torinesi e campionessa sabauda. Unisce grazia aristocratica e tempestosi incanti magnetici.',
    skillName: 'Incanto Reale & Pioggia di Cuori',
    skillKey: 'SPACE',
    skillDescription: 'Onda d\'urto di cuori che sconfigge i nemici trasformandoli in gianduiotti (+250 pt), attira ogni moneta e conferisce scudo per 4s.',
    skillCooldown: 11.0,
    tag: '💖 CHARM & SHIELD',
    color: '#ec4899',
    accentColor: '#f43f5e',
  },
  alessiuccia: {
    id: 'alessiuccia',
    name: 'Alessiuccia',
    subtitle: 'La Regina Glamour di Piazza San Carlo',
    description: 'Icona di stile e bellezza dei salotti torinesi. Il suo fascino scintillante abbaglia e spazza via qualsiasi ostacolo.',
    skillName: 'Fascio Glamour & Raggio Arcobaleno',
    skillKey: 'SPACE',
    skillDescription: 'Emette un bagliore abbagliante ad arco che incenerisce i nemici frontali nel raggio di 450px e cura +1 Cuore!',
    skillCooldown: 10.0,
    tag: '✨ GLAMOUR BEAM',
    color: '#fb7185',
    accentColor: '#f43f5e',
  },
  ludo: {
    id: 'ludo',
    name: 'Ludo',
    subtitle: 'La Hacker Punk & Beat Glitcher',
    description: 'Ribelle studentessa informatica di Palazzo Nuovo. Manipola circuiti e frequenze radio per generare tempeste EMP.',
    skillName: 'EMP Glitch Sonico',
    skillKey: 'SPACE',
    skillDescription: 'Scarica elettromagnetica a 360° che disattiva nemici e ostacoli vicini, ricaricando subito pistola e bomba!',
    skillCooldown: 9.0,
    tag: '⚡ EMP GLITCH',
    color: '#8b5cf6',
    accentColor: '#6d28d9',
  },
  ariannuccia: {
    id: 'ariannuccia',
    name: 'Ariannuccia',
    subtitle: 'L\'Esploratrice Alpina dei Boschi',
    description: 'Instancabile guida escursionistica dei sentieri di Superga e delle Alpi piemontesi. Agile, scattante e coraggiosa.',
    skillName: 'Scatto Fionda Alpina',
    skillKey: 'SPACE',
    skillDescription: 'Super scatto propulsivo in avanti a velocità 3x che trapassa nemici e spuntoni, rendendola invulnerabile per 3s.',
    skillCooldown: 8.5,
    tag: '🌲 ALPINE DASH',
    color: '#22c55e',
    accentColor: '#16a34a',
  },
  prato: {
    id: 'prato',
    name: 'Prato',
    subtitle: 'Il Botanico dei Giardini Reali',
    description: 'Mago delle essenze vegetali e guardiano della natura sabauda. I suoi rovi difendono chiunque con vigore.',
    skillName: 'Scudo di Rovi Rampicanti',
    skillKey: 'SPACE',
    skillDescription: 'Crea una barriera di rovi fioriti attorno al corpo per 5s che elimina i nemici al tocco e conferisce immunità.',
    skillCooldown: 12.0,
    tag: '🌿 BRAMBLE SHIELD',
    color: '#15803d',
    accentColor: '#166534',
  },
  sandrone: {
    id: 'sandrone',
    name: 'Sandrone',
    subtitle: 'Il Titano delle Fonderie FIAT',
    description: 'Fabbro possente e instancabile collaudatore di Mirafiori. Quando colpisce il suolo, trema tutta Torino.',
    skillName: 'Maglio Sismico d\'Acciaio',
    skillKey: 'SPACE',
    skillDescription: 'Colpo sismico titanico che spacca tutte le casse e annienta ogni nemico a terra nel raggio di 520px!',
    skillCooldown: 9.5,
    tag: '🔨 TITAN SMASH',
    color: '#64748b',
    accentColor: '#b91c1c',
  },
  vinzert: {
    id: 'vinzert',
    name: 'Vinzert',
    subtitle: 'Il Master DJ dei Murazzi Underground',
    description: 'Pioniere del sound elettronico torinese. I suoi drop sub-bass fanno vibrare le banchine del Po e le folle.',
    skillName: 'Subwoofer Bass Drop 808',
    skillKey: 'SPACE',
    skillDescription: 'Onda d\'urto sonora che spazza via i nemici a 360°, attiva il magnete monete e raddoppia i punti gianduiotti per 6s!',
    skillCooldown: 11.0,
    tag: '🎧 BASS DROP',
    color: '#eab308',
    accentColor: '#ca8a04',
  },
};

export const CHARACTER_LIST: CharacterConfig[] = Object.values(CHARACTERS);

export function getCharacterConfig(id: CharacterId): CharacterConfig {
  return CHARACTERS[id] || CHARACTERS.shhte;
}
